src/carts/urls.py
from django.urls import path
from . import views 

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view,
        add_to_cart_single_quantity,
        remove_from_cart_single_quantity,
        add_coupon_view,

)

app_name = 'carts'

urlpatterns = [
    
   	path('', cart_home, name='home'),
   	path('update/', cart_update, name='update'),
   	path('checkout/', checkout_home, name='checkout'),
    path('coupon/', add_coupon_view, name='coupon'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('add-to-cart/<slug:slug>/', add_to_cart_single_quantity, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>/', remove_from_cart_single_quantity, name='remove-from-cart'),
]

src/ecom/urls.py
  
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from addresses.views import (checkout_address_create_view, 
                            checkout_shipping_address_create_view, 
                            checkout_address_reuse_view,
                            checkout_shipping_address_update_view
                        )
from billing.views import payment_method_view, payment_method_createview
from accounts.views import login_page, guest_register_page, register_page, logout_view 


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', register_page, name='register'),
    url(r'^billing/payment/$', payment_method_view, name='billing-payment'),
    url(r'^billing/payment/create/$', payment_method_createview, name='billing-payment-create'),
    url(r'^register/guest/$', guest_register_page, name='guest_register'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/shpipping/address/update/$', checkout_shipping_address_update_view, name='checkout_shipping_address_update'),
    
    url(r'^checkout/shipping-address/create/$', checkout_shipping_address_create_view, name='checkout_shipping_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('', include('pages.urls')),
    path('product/', include('products.urls', namespace='products')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('search/', include('search.urls', namespace='search')),
]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/pages/urls.py
from django.urls import path
from . import views 

# from .views import (

# )

app_name = 'pages'

urlpatterns = [
    #path('list/', HomeView.as_view(), name='home'),
    path('', views.index, name='index'), #
    path('blog/list/', views.blog_list, name='list'), #blog/list
    path('shop/', views.shop, name='shop'),
    path('email/', views.email, name='email')
]

src/templates/partials/alerts.html
{% if messages %}

   {% for message in messages %} 
        <div class="container" id="message">
                <div class="alert alert-{{ message.tags }} alert-danger alert-dismissible text-center" role="alert">
                    <button type="button" class="close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>

                    </button>
                    <strong>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                           Error:
                        {% else %} 
                           {{ message.tags|title}}
                        {% endif %}
                    </strong>
                    {{ message }}
                </div>
        </div>
   {% endfor %}

{% endif %}

src/templates/partials/footer.html
{% load static %}

{% block content %}
<!-- Footer -->
<footer class="text-light">
    <div class="container">
        <div class="row">
            <div class="col-md-3 col-lg-4 col-xl-3">
                <h5>About</h5>
                <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                <p class="mb-0">
                    Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression.
                </p>
            </div>

            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto">
                <h5>Informations</h5>
                <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                <ul class="list-unstyled">
                    <li><a href="">Link 1</a></li>
                    <li><a href="">Link 2</a></li>
                    <li><a href="">Link 3</a></li>
                    <li><a href="">Link 4</a></li>
                </ul>
            </div>

            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto">
                <h5>Others links</h5>
                <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                <ul class="list-unstyled">
                    <li><a href="">Link 1</a></li>
                    <li><a href="">Link 2</a></li>
                    <li><a href="">Link 3</a></li>
                    <li><a href="">Link 4</a></li>
                </ul>
            </div>

            <div class="col-md-4 col-lg-3 col-xl-3">
                <h5>Contact</h5>
                <hr class="bg-white mb-2 mt-0 d-inline-block mx-auto w-25">
                <ul class="list-unstyled">
                    <li><i class="fa fa-home mr-2"></i> My company</li>
                    <li><i class="fa fa-envelope mr-2"></i> email@example.com</li>
                    <li><i class="fa fa-phone mr-2"></i> + 33 12 14 15 16</li>
                    <li><i class="fa fa-print mr-2"></i> + 33 12 14 15 16</li>
                </ul>
            </div>
            <div class="col-12 copyright mt-3">
                <p class="float-left">
                    <a href="#">Back to top</a>
                </p>
                <p class="text-right text-muted">created with <i class="fa fa-heart"></i> by <a href="https://t-php.fr/43-theme-ecommerce-bootstrap-4.html"><i>t-php</i></a> | <span>v. 1.0</span></p>
            </div>
        </div>
    </div>
</footer>


{% endblock %}

src/templates/partials/navbar.html
{% load static %}

{% block content %} 

{% url 'products:list' as product_list_url %}

<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark mb-5">
    <div class="container">
        <a class="navbar-brand" href="{{product_list_url}}">Dj Ecommerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-end" id="navbarsExampleDefault">
            <ul class="navbar-nav m-auto">
                <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                    <a class="nav-link" href="{{product_list_url}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{product_list_url}}">Product </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{product_list_url}}">Categories</a>
                </li>
                {% if user.is_authenticated %}
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">({{request.user}})Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>

            {% include 'search/snippets/search-form.html' %}
            <div class="form">
                <a class="btn btn-success btn-sm ml-3" href="{% url 'carts:home' %}">
                    <i class="fa fa-shopping-cart"></i> Cart
                    <span class="badge badge-light"><span class="navbar-cart-items">{{ request.session.cart_items }}</span></span>
                </a>
            </div>
        </div>
    </div>
</nav>

{% endblock %}