src/carts/urls.py
from django.urls import path
from . import views 

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view,
        add_to_cart_single_quantity,
        remove_from_cart_single_quantity,
        add_coupon_view,

)

app_name = 'carts'

urlpatterns = [
    
   	path('', cart_home, name='home'),
   	path('update/', cart_update, name='update'),
   	path('checkout/', checkout_home, name='checkout'),
    path('coupon/', add_coupon_view, name='coupon'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('add-to-cart/<slug:slug>/', add_to_cart_single_quantity, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>/', remove_from_cart_single_quantity, name='remove-from-cart'),
]

src/ecom/urls.py
  
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from addresses.views import (checkout_address_create_view, 
                            checkout_shipping_address_create_view, 
                            checkout_address_reuse_view,
                            checkout_shipping_address_update_view
                        )
from billing.views import payment_method_view, payment_method_createview
from accounts.views import login_page, guest_register_page, register_page, logout_view 


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', register_page, name='register'),
    url(r'^billing/payment/$', payment_method_view, name='billing-payment'),
    url(r'^billing/payment/create/$', payment_method_createview, name='billing-payment-create'),
    url(r'^register/guest/$', guest_register_page, name='guest_register'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/shpipping/address/update/$', checkout_shipping_address_update_view, name='checkout_shipping_address_update'),
    
    url(r'^checkout/shipping-address/create/$', checkout_shipping_address_create_view, name='checkout_shipping_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('', include('pages.urls')),
    path('product/', include('products.urls', namespace='products')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('search/', include('search.urls', namespace='search')),
]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/carts/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from products.models import Product, Color 

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.DecimalField(decimal_places=2, max_digits=10, default=0.00) 

    def __str__(self):
        return self.code


class CartManager(models.Manager):
	def new_or_get(self, request):
		cart_id = request.session.get("cart_id", None)
		qs = self.get_queryset().filter(id=cart_id, ordered=False)
		if qs.count() == 1:
			new_obj = False
			cart_obj = qs.first()
			if request.user.is_authenticated and cart_obj.user is None:
				cart_obj.user = request.user
				cart_obj.save()
		else:
			cart_obj = Cart.objects.new(user=request.user)
			new_obj = True
			request.session['cart_id'] = cart_obj.id
		return cart_obj, new_obj
	
	def new(self, user=None):
		user_obj = None
		if user is not None:
			if user.is_authenticated:
				user_obj = user
		return self.model.objects.create(user=user_obj)

class Cart(models.Model):
	user 		= models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
	products	= models.ManyToManyField(Product, blank=True)
	colors		= models.ManyToManyField(Color, blank=True)
	quantity 	= models.IntegerField(default=1)
	ordered 	= models.BooleanField(default=False)
	coupon 		= models.ForeignKey(Coupon, on_delete=models.SET_NULL, blank=True, null=True)
	total		= models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
	subtotal	= models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
	updated 	= models.DateTimeField(auto_now=True)
	timestamp 	= models.DateTimeField(auto_now_add=True)

	objects = CartManager()

	def __str__(self):
		return str(self.id)

	# def get_total_item_price(self):
	# 	return self.quantity * self.products.price 



	# total discount item price 
	# amout save 
	# final price


def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
	if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
		products = instance.products.all()
		total = 0
		for x in products:
			total += x.price 
		# print(total)
		if instance.coupon:
			total -= instance.coupon.amount
			print(total)

		if instance.subtotal != total:
			instance.subtotal = total
			instance.save() 

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)


def pre_save_cart_receiver(sender, instance, *args, **kwargs):
	if instance.subtotal > 0:
		instance.total = float(instance.subtotal) * float(1.08) # add taxes and delivery charge
	else:
		instance.total = 0.00


pre_save.connect(pre_save_cart_receiver, sender=Cart)

src/carts/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core.exceptions import ObjectDoesNotExist
from orders.models import Order
from orders.forms import CouponForm
from products.models import Product, Variation, Color, Size
from .models import Cart, Coupon
from billing.models import BillingProfile
from addresses.models import Address
from addresses.forms import AddressForm, ShippingAddressForm
from accounts.forms import LoginForm, GuestForm
from accounts.models import GuestEmail
# Create your views here.

def cart_create(user=None):
	cart_obj = Cart.objects.create(user=None)
	print("New Cart created")
	return cart_obj

def cart_home(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request) 
	# print(request.POST)
	# add into cart view
	# cart_id = request.session.get("cart_id", None)
	# qs = Cart.objects.filter(id=cart_id)
	# if qs.count() == 1:
	# 	print('Cart ID exists')
	# 	cart_obj = qs.first()
	# 	if request.user.is_authenticated and cart_obj.user is None:
	# 		cart_obj.user = request.user
	# 		cart_obj.save()
	# else:
	# 	cart_obj = Cart.objects.new(user=request.user)
	# 	request.session['cart_id'] = cart_obj.id 

	# add total 
	# products = cart_obj.products.all()
	# total = 0
	# for x in products:
	# 	total += x.price  
	# # print(total)
	# cart_obj.total = total
	# cart_obj.save()
	context = {
		"cart": cart_obj,
		"form": CouponForm
	}

	return render(request, "carts/home.html", context) 



def cart_update(request):
	product_id 	= request.POST.get('product_id')
	
	if product_id is not None:
		try:
			product_obj = Product.objects.get(id=product_id)
		except Product.DoesNotExist:
			# print("Product is gon?")
			return redirect("carts:home")
		cart_obj, new_obj = Cart.objects.new_or_get(request)
		if product_obj in cart_obj.products.all():
			cart_obj.products.remove(product_obj)
			added = False
		else:
			# print(product_obj.id)
			# print(cart_obj)
			cart_obj.products.add(product_obj.id)
			added = True
		request.session['cart_items'] = cart_obj.products.count()

		if request.is_ajax():
			print("Ajax call")
			json_data = {
				"added": added,
				"remove": not added,
				"cart_items_count": cart_obj.products.count()
			}
			return JsonResponse(json_data)
	return redirect("carts:home") 


def getShipping(request, order_obj, billing_profile):
	if order_obj is not None:
		# print(order_obj.id)
		# print(billing_profile)
		try:
			shipping_address = Address.objects.filter(
					billing_profile=billing_profile,
					address_type="shipping" 
				).first()

			shipping_address_data = {
				'name': str(shipping_address.first_name) + " " + str(shipping_address.last_name),
				'address':{
				'line1': shipping_address.address_line_1,
				'line2': shipping_address.address_line_2,
				'postal_code': shipping_address.postal_code,
				'city': shipping_address.city,
				'state': shipping_address.state,
				'country': shipping_address.country,
				},
			}
			return shipping_address_data
		except ObjectDoesNotExist:
			print("Not getting shipping address for stripe charge!")


def checkout_home(request):
	cart_obj, cart_created = Cart.objects.new_or_get(request) 
	if cart_created or cart_obj.products.count() == 0:
		return redirect("carts:home")  
	
	user = request.user
	billing_profile = None
	login_form = LoginForm()
	guest_form = GuestForm()
	address_form = AddressForm()
	shipping_form = ShippingAddressForm()
	billing_address_id = request.session.get("billing_address_id", None)
	shipping_address_id = request.session.get("shipping_address_id", None)

	billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)

	order_obj = None
	address_qs = None
	if billing_profile is not None:
		if request.user.is_authenticated:
			address_qs = Address.objects.filter(billing_profile=billing_profile)

		order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
		if shipping_address_id:
			order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
			del request.session["shipping_address_id"]
		if billing_address_id:
			order_obj.billing_address = Address.objects.get(id=billing_address_id)
			del request.session["billing_address_id"]
		if shipping_address_id or billing_address_id:
			order_obj.save() 


	if request.method == "POST":
		"check that order is done."
		is_done = order_obj.check_done()
		if is_done:
			#pass shipping address to strip mandotory
			shipping_address_data = getShipping(request, order_obj, billing_profile)
			# print(shipping_address_data)
			if shipping_address_data is not None:
				# call stripe charge method
				did_charge, charge_msg = billing_profile.charge(order_obj, shipping_address_data)
				if did_charge:
					order_obj.mark_paid()
					request.session['cart_items'] = 0
					del request.session['cart_id']
					return redirect("carts:success")
				else:
					print(charge_msg)
					return redirect("carts:checkout")
			# add custome error mdjango message
			return redirect("carts:checkout")

	context = {
		"object": order_obj,
		"billing_profile": billing_profile,
		"login_form": login_form,
		"guest_form": guest_form,
		"address_form": address_form,
		"shipping_form": shipping_form,
		"address_qs": address_qs

	}
	return render(request, "carts/checkout.html", context)

# Apply coupon code
def get_coupon(request, code):
    try:
        coupon = Coupon.objects.get(code=code)
        return coupon
    except ObjectDoesNotExist:
        messages.info(request, "This coupon does not exist")
        return redirect("carts:checkout")

def add_coupon_view(request):
	coupon_code 	= request.POST.get('coupon_code') 
	print(coupon_code)
	if coupon_code is not None:
		try:
			coupon_obj = get_coupon(request, coupon_code)
			cart_obj, cart_created = Cart.objects.new_or_get(request)
			cart_obj.coupon = coupon_obj
			cart_obj.save()
			print("coupon_code apply")
			return redirect("carts:checkout")
		except ObjectDoesNotExist:
			print("coupon_code not apply")
			messages.info(self.request, "You do not have an active order")
			return redirect("carts:checkout")

	return redirect("carts:checkout")





def checkout_done_view(request):
	context = {}
	return render(request, "carts/checkout-done.html", context)


def add_to_cart_single_quantity(request, slug):
	if slug is not None:
		try:
			product_obj = Product.objects.get(slug=slug)
		except Product.DoesNotExist:
			print("Product is gon?")
			return redirect("carts:home")
		cart_obj, new_obj = Cart.objects.new_or_get(request)
		if cart_obj.quantity >= 0:
			cart_obj.quantity += 1
			cart_obj.save()

	return redirect("carts:home") 




def remove_from_cart_single_quantity(request, slug):
	if slug is not None:
		try:
			product_obj = Product.objects.get(slug=slug)
		except Product.DoesNotExist:
			print("Product is gon?")
			return redirect("carts:home")
		cart_obj, new_obj = Cart.objects.new_or_get(request)
		if cart_obj.quantity >= 1:
			cart_obj.quantity -= 1
			cart_obj.save()

	return redirect("carts:home")

src/carts/templates/carts/checkout-done.html
{% extends 'base.html' %} 

{% load static %}


{% block stylesheet %}

{% endblock %}


{% block content %} 
<div class="container mt-5">
	 <div class="col-6 mx-auto py-5 text-center">
	 	<h1 class="display-1"> Tnank you for order !!!</h1>
	 </div>
</div>

{% endblock %}

src/carts/templates/carts/checkout.html
{% extends 'base.html' %} 

{% load static %}


{% block stylesheet %}

{% endblock %}


{% block content %} 

<div class="container mt-5">
	<br />
<!-- shipping Address : {{object.shipping_address}} <br />
{{object.order_id}} -- {{object.cart}} -->

	{% if not billing_profile %}
		<div class="row text-center">{% csrf_token %} 
			<div class="col-12 col-md-6">
				<p class="lead">Login</p>
				{% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri  %}
			</div>

			<div class="col-12 col-md-6">
				<p class="lead">Continue as Guest </p>
				{{guest_register_url}}
				{% url 'guest_register' as guest_register_url %}
				{% include 'accounts/snippets/form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url  %}
			</div>
			
		</div>	


	{% else %}


		{% if not object.shipping_address %}
		<div class="row">
			<div class="col-12">
				<p class="lead">Shipping Address </p>
				<hr />
			</div>
			<div class="col-md-6">
				
			{% url 'checkout_shipping_address_create' as checkout_address_create %}
				{% include 'addresses/form.html' with form=shipping_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping' %}
			</div>
			
			<div class="col-md-6">
				{% url 'checkout_address_reuse' as checkout_address_reuse %}
				{% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='shipping' action_url=checkout_address_reuse %}

				
			</div>

		</div>

		{% elif  not object.billing_address %}
		<div class="row">
			<div class="col-12">
				<p class="lead">Billing Address </p>
				<hr />
			</div>
			<div class="col-md-6">
				{% url 'checkout_address_create' as checkout_address_create %}
				{% include 'addresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing' %}

			</div>
			<div class="col-md-6">
				{% url 'checkout_address_reuse' as checkout_address_reuse %}
				{% include 'addresses/prev_addresses.html' with address_qs=address_qs next_url=request.build_absolute_uri address_type='billing' action_url=checkout_address_reuse %}
				<a href="#">Change Shipping Address </a>
			</div>
		</div>
		
		{% else %}

	   	 <h1> Finalize Checkout: </h1>
	   	 <p>Cart Item :{% for product in object.cart.products.all %} {{product}} {% if not forloop.last %}, {% endif %} {% endfor %}</p>
	   	 <p>Shipping Address : {{object.shipping_address.get_address }} | <a data-toggle="modal" data-target="#shippingModal" href="#">Change Address </a></p>
	   	 <p>Billing Address: {{object.billing_address.get_address }} | <a href="#">Change Address </a></p>
		 <p>Cart Total : {{object.cart.total}}</p>
	    <p>Shipping Total : {{object.shipping_total}}</p>
	    <p>Order Total : {{object.total}}</p>
	    <form class="form" method="POST" action="#">
	    	{% csrf_token %}
	    	<button type="submit" class="btn btn-success">Proceed To Pay</button>
	    </form>
	    {% endif %}									

    {% endif %}
</div>

<!-- #modal -->
<!-- Modal -->
<div class="modal fade" id="shippingModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
<form action="{% url 'checkout_shipping_address_update' %}" method="POST">
 	{% csrf_token %} 
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="shippingModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
  		<input type="hidden" name="address_id" value="{{object.shipping_address.id}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required="True">
      	<input type="text" name="address_line_1" value="{{object.shipping_address.address_line_1}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required="True">
      	<input type="text" name="address_line_2" value="{{object.shipping_address.address_line_2}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required="True">
      	<input type="text" name="city" value="{{object.shipping_address.city}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required="True">
      	<input type="text" name="state" value="{{object.shipping_address.state}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required="True">
  		<input type="text" name="country" value="{{object.shipping_address.country}}" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" required="True">
         
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
  </form>
</div>
{% endblock %}

src/carts/templates/carts/home.html
{% extends 'base.html' %} 

{% load static %}


{% block stylesheet %}

{% endblock %}

{% block content %} 


<div class="container mt-5">
    <h1> Cart </h1>
    {% if cart.products.exists %}
    <table class="table">
	  <thead>
	    <tr>
	      <th scope="col">#</th>
	      <th scope="col">Product Name</th>
	      <th scope="col">Product Price</th>
	      <th scope="col">Quantity</th>
	    </tr>
	  </thead>
	  <tbody>
	  	{% for product in cart.products.all %}
	    <tr>
	      <th scope="row">{{ forloop.counter }}</th>
	      <td><a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
	      	{% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True %}
	      </td>
	      <td><a href="{% url 'carts:remove-from-cart' slug=product.slug %}"> <i class="fa fa-minus mr-2"></i></a>{{ cart.quantity }}<a href="{% url 'carts:add-to-cart' slug=product.slug %}"><i class="fa fa-plus ml-2"></i></a></td>
	      <td>{{ product.price }}</td>
	    </tr>
	    {% endfor %}
	    <tr>
	    	<td colspan="3">
	    		<form class="coupon_code" method="POST" action="{% url 'carts:coupon' %}">
	    			{% csrf_token %}
		    		<input type="text" name="coupon_code", placeholder="coupon code">
		    		<button type="submit" class="btn btn-info btn small">Apply</button>
	    		</form>
	    	</td>
	     <!--  <td colspan="2"></td> -->
	      <td><b>subtotal</b>: {{ cart.subtotal }}</td>
	      <!-- <td><b>subtotal</b>: {{ cart.get_total_item_price }}</td> -->
	    </tr>
	    <tr>
	       <td colspan="3"></td>
	      <td><b>total</b>: {{ cart.total }}</td>
	    </tr>
	      <tr>
	       <td colspan="3"></td>
	      <td><a class="btn btn-success btn-small" href="{% url 'carts:checkout' %}">Checkout</a></td>
	    </tr>
	  </tbody>
	</table>
	{% else %}
	 <p class="lead">No item in cart!</p>
	{% endif %}
</div>

{% endblock %}

{% block javascript %}
<!-- <script type="text/javascript">
 	$(document).ready(function(){
 		var productForm = $(".coupon_code")
 		productForm.submit(function(event){
 			event.preventDefault();
 			let thisForm = $(this)
 			let actionEndpoint = thisForm.attr("action")
 			let formData = thisForm.serialize()

 			$.ajax({
 				url:actionEndpoint,
 				method: 'POST',
 				data: formData,

 				success: function(data){
 					console.log("success");
 					let submitSpan = thisForm.find('.submit-span')
 					if (data.added){
 						submitSpan.html("In cart <button type='submit' class='btn btn-info'>Remove</button>")
 					}else{
 						submitSpan.html("<button type='submit'  class='btn btn-success'>Add to cart</button>")
 					}
 					let navbarCartCount = $(".navbar-cart-items")
 					navbarCartCount.text(data.cart_items_count)
 				},
 				error: function(errorData){
 					console.log("error");
 				}
 			})
 		})
 	})
 </script> -->
{% endblock %}