src/carts/urls.py
from django.urls import path
from . import views 

from .views import (
        cart_home,
        cart_update,
        checkout_home,
        checkout_done_view,
        add_to_cart_single_quantity,
        remove_from_cart_single_quantity,
        add_coupon_view,

)

app_name = 'carts'

urlpatterns = [
    
   	path('', cart_home, name='home'),
   	path('update/', cart_update, name='update'),
   	path('checkout/', checkout_home, name='checkout'),
    path('coupon/', add_coupon_view, name='coupon'),
    path('checkout/success/', checkout_done_view, name='success'),
    path('add-to-cart/<slug:slug>/', add_to_cart_single_quantity, name='add-to-cart'),
    path('remove-from-cart/<slug:slug>/', remove_from_cart_single_quantity, name='remove-from-cart'),
]

src/ecom/urls.py
  
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static

from addresses.views import (checkout_address_create_view, 
                            checkout_shipping_address_create_view, 
                            checkout_address_reuse_view,
                            checkout_shipping_address_update_view
                        )
from billing.views import payment_method_view, payment_method_createview
from accounts.views import login_page, guest_register_page, register_page, logout_view 


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^login/$', login_page, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', register_page, name='register'),
    url(r'^billing/payment/$', payment_method_view, name='billing-payment'),
    url(r'^billing/payment/create/$', payment_method_createview, name='billing-payment-create'),
    url(r'^register/guest/$', guest_register_page, name='guest_register'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/shpipping/address/update/$', checkout_shipping_address_update_view, name='checkout_shipping_address_update'),
    
    url(r'^checkout/shipping-address/create/$', checkout_shipping_address_create_view, name='checkout_shipping_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    path('', include('pages.urls')),
    path('product/', include('products.urls', namespace='products')),
    path('cart/', include('carts.urls', namespace='carts')),
    path('search/', include('search.urls', namespace='search')),
]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

src/products/urls.py
from django.urls import path
from . import views 

from .views import (
	ProductListView,
	#ProductDetailtView,
	ProductSlugDetailtView,
	#ProductFeaturedListView,
	#ProductFeaturedDetailtView,

)

app_name = 'products'

urlpatterns = [
    
    #path('featured/', ProductFeaturedListView.as_view(), name='featured-list'),
    #path('featured/<int:pk>/', ProductFeaturedDetailtView.as_view(), name='featured-detail'),
    #path('detail-c/<int:pk>/', ProductDetailtView.as_view(), name='detail'),
    #path('list/', views.product_list_view, name='product-list'), #fucntion view
    #path('detail/<int:pk>/', views.product_detail_view, name='product-detail'), #fucntion view
   	path('', ProductListView.as_view(), name='list'),
   	path('<slug:slug>/', ProductSlugDetailtView.as_view(), name='detail'),
]

src/products/models.py
import random
import os
from django.db.models.signals import pre_save, post_save
from django.db.models import Q
from django.db import models
from django.urls import reverse
from ecom.utils import unique_slug_generator

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


def get_filename_ext(filepath):
	base_name 	= os.path.basename(filepath)
	name, ext 	= os.path.splitext(base_name)
	return name, ext 

def upload_image_path(instance, filename):
	# print(instance)
	# print(filename)
	new_filename = random.randint(1, 466565634020)
	name, ext = get_filename_ext(filename)
	final_filename = '{filename}{new_filename}{ext}'.format(filename=filename, new_filename=new_filename, ext=ext)
	return "products/{new_filename}/{final_filename}".format(new_filename=new_filename, final_filename=final_filename)



class Size(models.Model):
	name  	= models.CharField(max_length=120)
	
	def __str__(self):
		return self.name	

class Color(models.Model):
	name  	= models.CharField(max_length=120)
	
	def __str__(self):
		return self.name	
# variation 5
#  images
#	size
# 	color
#	price 
#	

class Variation(models.Model):
	color = models.ForeignKey(Color, null=True, blank=True, on_delete=models.CASCADE)
	size  = models.ForeignKey(Size, null=True, blank=True, on_delete=models.CASCADE)
	image = models.ImageField(upload_to=upload_image_path, null=True, blank=True)
	price = models.DecimalField(decimal_places=2, max_digits=10, default=0.00) 


	def __str__(self):
		return str(self.id)



# Create your models here.
class ProductQuerySet(models.QuerySet):
	def active(self):
		return self.filter(active=True)
	def featured(self):
		return self.filter(featured=True, active=True)

	def search(self, query):
		lookups = 	(Q(title__icontains=query) | 
					Q(description__icontains=query)|
					Q(tag__title__icontains=query)
					)	
		return self.filter(lookups).distinct()


class ProductManager(models.Manager):
	def get_queryset(self):
		return ProductQuerySet(self.model, using=self._db) 

	def all(self):
		return self.get_queryset().active()

	def featured(self): #Product.objects.featured()
		return self.get_queryset().featured()
 
	def get_by_id(self, id): 
		qs = self.get_queryset().filter(id=id)
		if qs.count() == 1:
			return qs.first()
		return None
	def search(self, query):
		lookups = Q(title__icontains=query) | Q(description__icontains=query)
		      #Q(tag__name__icontains=query) 
		      # t-shirt t shirt tshirt
		return self.get_queryset().active().search(query)



class Product(models.Model):
	title			= models.CharField(max_length=120)
	slug			= models.SlugField(blank=True, unique=True)
	category 		= models.CharField(choices=CATEGORY_CHOICES, max_length=2, blank=True, null=True)
	description		= models.TextField()
	price			= models.DecimalField(decimal_places=2, max_digits=10, default=0.00) 
	discount_price 	= models.FloatField(blank=True, null=True)
	image			= models.ImageField(upload_to=upload_image_path, null=True, blank=True)
	size			= models.ManyToManyField(Size, blank=True)
	color			= models.ManyToManyField(Color, blank=True)
	featured 		= models.BooleanField(default=False)
	active 			= models.BooleanField(default=True)


	objects = ProductManager()

	def get_absolute_url(self):
		#return "{slug}/".format(slug=self.slug)
		return reverse("products:detail", kwargs={"slug": self.slug})

	def __str__(self):
		return self.title 


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

pre_save.connect(product_pre_save_receiver, sender=Product) 

src/products/views.py
from django.http import Http404
from django.views.generic import ListView,DetailView
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from .models import Product 
from carts.models import Cart


class ProductFeaturedListView(ListView):
	#queryset = Product.objects.all() 
	template_name = "products/list.html" 

	def get_queryset(self, *args, **kwargs):
		request = self.request
		return Product.objects.all().featured()

class ProductFeaturedDetailtView(DetailView):
	queryset = Product.objects.all().featured() 
	template_name = "products/featured-detail.html" 

	# def get_queryset(self, *args, **kwargs):
	# 	request = self.request
	# 	return Product.objects.featured()

	


class ProductListView(ListView):
	#queryset = Product.objects.all() 
	template_name = "products/list.html" 

	# def get_context_data(self, *args, **kwargs):
	# 	context = super(ProductListView, self).get_context_data(*args, **kwargs)
	# 	print(context)
	# 	return context 

	def get_queryset(self, *args, **kwargs):
		request = self.request
		qs = Product.objects.all()
		print(qs)
		return Product.objects.all()

def product_list_view(request):
	queryset = Product.objects.all()
	context = {
		'object_list': queryset
	}
	return render(request, "products/list.html", context)


class ProductSlugDetailtView(DetailView):
	#queryset = Product.objects.all() 
	#print("data:", queryset)
	template_name = "products/detail.html"  

	def get_context_data(self, *args, **kwargs):
		context = super(ProductSlugDetailtView, self).get_context_data(*args, **kwargs)
		cart_obj, new_obj = Cart.objects.new_or_get(self.request)
		context['cart'] = cart_obj 
		return context

	# def get_absolute_url(self):
	# 	return reverse('detail-slug', kwargs={'slug': self.slug}) 

	def get_object(self, *args, **kwargs):
		request = self.request
		slug = self.kwargs.get('slug')
		#instance = get_object_or_404(Product, slug=slug, active=True)
		try:
			instance = Product.objects.get(slug=slug, active=True)
		except Product.DoesNotExist:
			raise Http404("Not found..")
		except Product.MultipleObjectsReturned:
			qs = Product.objects.filter(slug=slug, active=True)
			instance = qs.first()
		except:
			raise Http404("Uhhmmm ")
		return instance


class ProductDetailtView(DetailView):
	queryset = Product.objects.all() 
	template_name = "products/detail.html" 

	def get_context_data(self, *args, **kwargs):
		context = super(ProductDetailtView, self).get_context_data(*args, **kwargs)
		print(context)
		#context["abc"] = 123
		return context  

	def get_object(self, *args, **kwargs):
		request = self.request
		pk = self.kwargs.get('pk')
		instance = Product.objects.get_by_id(pk)
		if instance is None:
			raise Http404("Product not found.")
		return instance 

	# def get_queryset(self, *args, **kwargs):
	# 	request = self.request
	# 	pk = self.kwargs.get('pk')
	# 	return Product.objects.filter(pk=pk)


def product_detail_view(request, pk=None, *args, **kwargs):
	#instance = Product.objects.get(pk=pk) #is = pk
	#instance = get_object_or_404(Product, pk=pk)
	# try:
	# 	instance = Product.objects.get(id=pk)
	# except Product.DoesNotExist:
	# 	raise Http404("Product not found!!")
	# except:
	# 	print("Huu?") 

	instance = Product.objects.get_by_id(pk)
	if instance is None:
		raise Http404("Product not found!!")
	#print(instance)

	# qs = Product.objects.filter(id=pk)
	# if qs.exists() and qs.count() == 1:
	# 	instance = qs.first()
	# else:
	# 	raise Http404("Product not found!!")
	


	context = {
		'object': instance
	}
	return render(request, "products/detail.html", context)

src/products/templates/products/snippets/card.html
<div class="card" style="">
	{% if instance.image %}
	  <a href="{{ instance.get_absolute_url }}">
	  	<img src="{{ instance.image.url }}" width="60%" height="60%" class="card-img-top img-fluid" alt="{{ instance.title }} logo">
		</a>
	  {% endif %}
	  <div class="card-body">
	    <h5 class="card-title">{{instance.title}}</h5>
	    <p class="card-text">{{instance.description}}</p>
	    <a href="{{ instance.get_absolute_url }}" class="btn btn-primary">View</a>
	    <!-- <a href="{% url 'products:detail' slug=instance.slug %}" class="btn btn-warning">Shorcut URL</a> -->
	  </div>
</div>

src/products/templates/products/snippets/not-product-variation.html
not variant size: {{product.size.count}}
				 {% if product.color.count > 0 %}
				 <div class="color">
				 	<div class="form-group">
					    <label for="exampleFormControlSelect1">ColorNotVarient</label>
					    <select class="form-control" id="exampleFormControlSelect1" required>
					    	{% for var in product.color.all %}
					      	<option value="{{var}}">{{var}}</option>
					      	{% endfor %}
					    </select>
					  </div>
				</div>
				 {% endif %}

				  {% if product.size.count > 0 %}
				 <div class="color">
				 	<div class="form-group">
					    <label for="exampleFormControlSelect1">SizeNotVarient</label>
					    <select class="form-control" id="exampleFormControlSelect1" required="True">
					    	{% for var in product.size.all %}
					      		<option value="{{var}}">{{var}}</option>
					      	{% endfor %}
					    </select>
					  </div>
				</div>
				 {% endif %}

src/products/templates/products/snippets/product-variation.html
variant: {{product.variation.count}}
				{% if product.variation.count > 0 %}
				 <div class="size">
				 	<div class="form-group">
					    <label for="exampleFormControlSelect1">Color</label>
					    <select class="form-control" id="exampleFormControlSelect1" required="True">
				 		{% for var in product.variation.all %}
					      	<option>{{var.color}}</option>
					     {% endfor %}
					    </select>
					  </div>
				 </div>
				 {% endif %}

				 {% if product.variation.count > 0 %}
				 <div class="color">
				 	<div class="form-group">
					    <label for="exampleFormControlSelect1">Size</label>
					    <select class="form-control" id="exampleFormControlSelect1" required="True">
					      {% for var in product.variation.all %}
					      	<option value="{{var.size}}">{{var.size}}</option>
					     {% endfor %}
					    </select>
					  </div>
				</div>
				 {% endif %}

src/products/templates/products/snippets/update-cart.html
<form class="form-product-ajax" method="POST" action="{% url 'carts:update' %}" class="form">
	 {% csrf_token %}
    <input type="hidden" name='product_id' value="{{ product.id }}">
   		{% if in_cart %}
   			<button type="submit" class="btn btn-link btn-sm" style="padding: 0px; cursor: pointer;">Remove</button>
   		{% else %}
   		<span class="submit-span">
			{% if product in cart.products.all %}b
			  	In cart <button type="submit" class="btn btn-link">Remove</button>
			{% else %}
				<!-- product variation -->
				{% include 'products/snippets/product-variation.html' with product=object cart=cart %}

				<!-- not product variation -->
				 {% include 'products/snippets/not-product-variation.html' with product=object cart=cart %}
				<!-- quantity -->
				 <div class="quantity">
				 	<div class="form-group">
					    <label for="exampleFormControlSelect1">Quantity</label>
					    <select class="form-control" id="exampleFormControlSelect1" required="True">
					      	<option value="1" selected>1</option>
					      	<option value="2" >2</option>
					      	<option value="3" >3</option>
					      	<option value="4" >4</option>
					      	<option value="5" >5</option>
					      	<option value="6" >6</option>
					    </select>
					  </div>
				</div>
				<button type="submit"  class="btn btn-success">Add to cart</button>
			{% endif %}
		</span>
		{% endif %}
</form>